---
- name: Deploy and Run Test App
  hosts: docker_server
  gather_facts: true
  become: true

  tasks:
    - name: Clone the Git repository
      git:
        repo: https://github.com/Krishnarawat403/testapp-ansible.git
        dest: /root/project
      become: yes

    - name: Update Package Cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Start the Docker service
      systemd:
        name: docker
        state: started
      become: yes

    - name: Build Docker image
      command: docker build -t app /root/project/backend
      become: yes

    - name: Run Docker container
      docker_container:
        name: testapp_container
        image: app
        state: started
        ports:
          - "5000:5000"

  handlers:
    - name: Restart Docker service
      systemd:
        name: docker
"site.yml" 49L, 984B
